version: 2
updates:

- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    day: monday
  allow:
    - dependency-type: "direct"
  open-pull-requests-limit: 0

- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: weekly
    day: monday
  allow:
    - dependency-type: "direct"
  open-pull-requests-limit: 0
  ignore:
    - dependency-name: "chrono"

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: weekly
    day: monday
  open-pull-requests-limit: 10
  groups:
    github-actions:
      patterns:
        - "*"
  commit-message:
    prefix: "ci"
  labels:
    - "chore"
    - "dependencies"
    - "github_actions"
