name: Rust checks
permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: '0 7 * * 1'
  workflow_dispatch:

jobs:
  check:
    name: Rust Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: prefix-dev/setup-pixi@1b2de7f3351f171c8b4dfeb558c639cb58ed4ec0 # v0.9.5
        with:
          pixi-version: v0.63.2
          cache: true
          frozen: true
          cache-write: ${{ github.ref == 'refs/heads/main' }}
          environments: dev

      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          shared-key: "gha"
          # Don't cache for cargo check
          save-if: false

      - name: Run cargo check
        run: |
          pixi run -e dev cargo check --workspace --locked

  lints:
    # Only run tests if code looks OK
    needs: check
    name: Rust Lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: prefix-dev/setup-pixi@1b2de7f3351f171c8b4dfeb558c639cb58ed4ec0 # v0.9.5
        with:
          pixi-version: v0.63.2
          cache: true
          frozen: true
          cache-write: ${{ github.ref == 'refs/heads/main' }}
          environments: dev

      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          shared-key: "gha"
          # Don't cache for cargo fmt/clippy
          save-if: false

      - name: Run cargo fmt
        run: |
          pixi run -e dev --frozen cargo fmt --all --check

      - name: Run cargo clippy
        run: |
          pixi run -e dev --frozen cargo clippy --locked --all-features --tests -- -D warnings

  test:
    # Only run tests if code looks OK
    needs: check
    name: Rust Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1.0.6
        with:
            toolchain: 1.87.0
            override: true
            profile: minimal

      - uses: prefix-dev/setup-pixi@1b2de7f3351f171c8b4dfeb558c639cb58ed4ec0 # v0.9.5
        with:
          pixi-version: v0.63.2
          cache: true
          frozen: true
          cache-write: ${{ github.ref == 'refs/heads/main' }}
          environments: dev

      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          shared-key: "gha"
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - run: pixi run tests-r
