name: Codecov

concurrency:
  group: codecov-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  run:
    name: Codecov
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        fetch-depth: 0
        fetch-tags: true

    - uses: prefix-dev/setup-pixi@5185adfbffb4bd703da3010310260805d89ebb11 # v0.9.6
      with:
        pixi-version: v0.69.0
        locked: true
        cache: true
        cache-write: false
        environments: dev

    - name: Generate coverage report
      run: |
        pixi reinstall -e dev --locked NLR-reVRt
        pixi run -e dev --locked tests

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@e79a6962e0d4c0c17b229090214935d2e33f8354 # v6.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.xml
        flags: unittests
        env_vars: OS,PYTHON
        name: codecov-umbrella
        fail_ci_if_error: false
        verbose: true
